### ISSUE TITLE
[Q]: How to pull devenv-runtimes through corporate proxy

### ISSUE THREAD

**Issue by Kiremai974** [eclipse-velocitas/devenv-runtimes#49] opened 2023-10-11 09:14 UTC
### Question

Hello, I have a setup where I am trying to run the seatadjuster app on Linux but pulling the devenv-runtimes with the velocitas CLI tool does not seem to work through my company proxy server which uses ssl interception. Logs say : 

[29675 ms] Start: Run in container: /bin/sh -c bash .devcontainer/scripts/onCreateCommand.sh
#######################################################
#######################################################
Initializing Velocitas packages ...
... Downloading package: 'devenv-runtimes:v2.2.2'
... > Running post init hook for 'runtime-local'
Running 'install-deps'... !
 ›   Error: Program returned exit code: 1
Syncing Velocitas components!
Cannot find component devenv-github-workflows:v4.1.1. Please upgrade or init first!
    Error: Cannot find component devenv-github-workflows:v4.1.1
    
Do you know how I can work around this problem? It works perfectly fine when I use a normal network without proxying.

**Comment by Kiremai974** [comment] 2023-10-11 09:31
I have my company http/https proxy setup in ~/.docker/config.json.

As a temporary solution I added my CA certificates to the container image like this in the Dockerfile
```dockerfile

COPY ssl-certs/*.crt /usr/local/share/ca-certificates/
COPY ssl-certs/*.crt /usr/share/ca-certificates/
RUN update-ca-certificates
``` 
and added this to the script `onCreateCommand.sh` before ``velocitas init``

```shell
# tmp fix work through ssl interception of proxy...
pip3 config set global.trusted-host \
    "pypi.org files.pythonhosted.org pypi.python.org github.com" \
    --trusted-host=pypi.python.org \
    --trusted-host=pypi.org \
    --trusted-host=files.pythonhosted.org \
    --trusted-host=github.com
``` 

As it is clearly stated to not modify these files and to configure by editing only .velocitas.json, how would you do this in a clean way so that these files are not reset after building the container?

**Comment by MP91** [comment] 2023-10-16 10:28
Hey @Kiremai974,

could please run 
`sudo rm -rf ~/.velocitas`
`velocitas init -v`
?

Just to be sure that it is really a problem with the proxy and not something else.

**Comment by Kiremai974** [comment] 2023-10-18 09:01
> Hey @Kiremai974,
> 
> could please run `sudo rm -rf ~/.velocitas` `velocitas init -v` ?
> 
> Just to be sure that it is really a problem with the proxy and not something else.

Hi, it gets stuck for a while and after that gives me those errors : 
```shell
sudo rm -rf ~/.velocitas && velocitas init -v
Initializing Velocitas packages ...
... Downloading package: 'devenv-runtimes:v2.2.2'
GitError: Cloning into '/home/vscode/.velocitas/packages/devenv-runtimes/v2.2.2'...
fatal: unable to access 'https://github.com/eclipse-velocitas/devenv-runtimes/': Failed to connect to github.com port 443 after 130644 ms: Connection timed out

    at Object.action (/snapshot/cli/node_modules/simple-git/dist/cjs/index.js:1300:25)
    at PluginStore.exec (/snapshot/cli/node_modules/simple-git/dist/cjs/index.js:1335:29)
    at /snapshot/cli/node_modules/simple-git/dist/cjs/index.js:1734:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/snapshot/cli/node_modules/simple-git/dist/cjs/index.js:1732:16)
    at GitExecutorChain.<anonymous> (/snapshot/cli/node_modules/simple-git/dist/cjs/index.js:1716:44)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/cli/node_modules/simple-git/dist/cjs/index.js:55:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  task: {
    commands: [
      'clone',
      'https://github.com/eclipse-velocitas/devenv-runtimes',
      '/home/vscode/.velocitas/packages/devenv-runtimes/v2.2.2'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
Cannot find component devenv-runtimes:v2.2.2. Please upgrade or init first!
    Error: Cannot find component devenv-runtimes:v2.2.2

```

**Comment by MP91** [comment] 2023-10-18 09:55
This seems really like a proxy or at least connection issue.

@kse3hi could you help fixing the issue?

**Comment by kse3hi** [comment] 2023-10-19 12:47
Hi @Kiremai974 , have you checked our documentation in regards to Proxy: https://eclipse.dev/velocitas/docs/tutorials/quickstart/behind_proxy/

If yes, try to only follow the instructions and remove all additional configurations.

Please provide feedback, if it works with basic Proxy Setup (at least in our test environment we were not able to reproduce the same behavior).

Can you also please describe your environment in details:
OS: ?
VSCode Version: ?
DevContainer extension version: ?
Template commit: ?

**Comment by Kiremai974** [comment] 2023-10-19 12:51
> Hi @Kiremai974 , have you checked our documentation in regards to Proxy: https://eclipse.dev/velocitas/docs/tutorials/quickstart/behind_proxy/

Hey, yes I read that documentation and followed the instructions there without additional configurations, only the template repository, with the seat adjuster example. I came up with my quick fix thanks to that (modifying the config files in .devcontainer folder)  :

> I have my company http/https proxy setup in ~/.docker/config.json.
> 
> As a temporary solution I added my CA certificates to the container image like this in the Dockerfile
> 
> ```dockerfile
> COPY ssl-certs/*.crt /usr/local/share/ca-certificates/
> COPY ssl-certs/*.crt /usr/share/ca-certificates/
> RUN update-ca-certificates
> ```
> 
> and added this to the script `onCreateCommand.sh` before `velocitas init`
> 
> ```shell
> # tmp fix work through ssl interception of proxy...
> pip3 config set global.trusted-host \
>     "pypi.org files.pythonhosted.org pypi.python.org github.com" \
>     --trusted-host=pypi.python.org \
>     --trusted-host=pypi.org \
>     --trusted-host=files.pythonhosted.org \
>     --trusted-host=github.com
> ```
> 
> As it is clearly stated to not modify these files and to configure by editing only .velocitas.json, how would you do this in a clean way so that these files are not reset after building the container?

but I consider it temporary because both these files are entirely reset after the container is built.

> Can you also please describe your environment in details:

OS: Debian 12
VSCode Version: 1.83.0
DevContainer extension version: v0.315.1
Template commit: https://github.com/eclipse-velocitas/vehicle-app-python-template/commit/4be9c83043add346a7fdc850939b7b2ee47b5567

**Comment by kse3hi** [comment] 2023-10-20 07:05
Hi @Kiremai974 , 

> but I consider it temporary because both these files are entirely reset after the container is built.

We have few suggestions to avoid this behavior:

1. Just fork https://github.com/eclipse-velocitas/devenv-devcontainer-setup with your adaption and feed it to velocitas.json in your project as package instead of origin one: https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/main/.velocitas.json
Unfortunately it will drop our automatic support, and you will need to update it manually.

2. Just create feature as PR suggestion to add some extension scripts:
```
ON_CREATE_EXTENSION_SCRIPT = ".devcontainer/extensions/on-create.sh"

if [ -e "$ON_CREATE_EXTENSION_SCRIPT" ]; then
    bash $ON_CREATE_EXTENSION_SCRIPT
fi
```
Later you can control this custom script on your own.

Any commitment is appreciated :)

**Comment by kse3hi** [comment] 2023-10-25 07:52
@Kiremai974 , I've created feature for ability to perform custom scripts in different steps of lifecycle management: https://github.com/eclipse-velocitas/devenv-devcontainer-setup/issues/44

Please let us know, if we able to help something else? If not I will close this question for now and we will track next activity in feature.

**Closed as completed by kse3hi** 2023-10-25 07:52 UTC
Labels: question
